#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

PYAPIDIR=$TEST_ROOT_DIR/../../contrib/Python
PYTHON=/usr/local/anaconda2/bin/python

pushd $PYAPIDIR
echo Current dir: $PYAPIDIR

$PYTHON -c "import sys; print('Python: %s'%sys.version)"
$PYTHON -c "import numpy; print('NumPy: %s'%numpy.version.full_version)"
$PYTHON -c "import pytest; print('PyTest: %s'%pytest.__version__)"

export CNTK_EXECUTABLE_PATH=$TEST_CNTK_BINARY
run py.test -k graph

if [ "$?" -eq "0" ]; then
  echo "__COMPLETED__"
fi

popd

