#!/bin/bash

. $TEST_ROOT_DIR/run-test-common

PYAPIDIR=$TEST_ROOT_DIR/../../contrib/Python

pushd $PYAPIDIR
echo Current dir: $PYAPIDIR

export CNTK_EXECUTABLE_PATH=$TEST_CNTK_BINARY
run py.test -k graph

if [ "$?" -eq "0" ]; then
  echo "__COMPLETED__"
fi

popd

